// GENERATED by tools/build-manifest.mjs — do not edit by hand.
// 7 item(s). Rebuild: node tools/build-manifest.mjs
window.GALLERY_ITEMS = [
  {
    "type": "youtube",
    "ts": "2024.03.14 18:30",
    "year": 2024,
    "title": "Big Buck Bunny",
    "desc": "Golden hour catches the dust suspended mid-air in the empty warehouse.",
    "id": "aqz-KE-bpKQ"
  },
  {
    "type": "youtube",
    "ts": "2024.03.09 08:15",
    "year": 2024,
    "title": "Elephants Dream",
    "desc": "The light changed and everyone looked up at once.",
    "id": "YE7VzlLtp-4"
  },
  {
    "type": "youtube",
    "ts": "2024.03.02",
    "year": 2024,
    "title": "Tears of Steel",
    "desc": "Storm light over the reservoir just before the rain arrived.",
    "id": "TKNjNatvOuA",
    "link": "https://www.magnumphotos.com"
  },
  {
    "type": "youtube",
    "ts": "2024.01.22 16:40",
    "year": 2024,
    "title": "Cosmos Laundromat",
    "desc": "First frost of the season traced along the windowpane.",
    "id": "eRsGyueVLvQ"
  },
  {
    "type": "youtube",
    "ts": "2024.01.06",
    "year": 2024,
    "title": "Sintel",
    "desc": "Rain-slicked cobblestones, a single red umbrella.",
    "id": "WhWc3b3KhnY"
  },
  {
    "type": "youtube",
    "ts": "2023.11.18 11:05",
    "year": 2023,
    "title": "Caminandes: Gran Desierto",
    "desc": "Nobody told the sunflowers summer was nearly over.",
    "id": "RR36BkHqAbo"
  },
  {
    "type": "youtube",
    "ts": "2023.11.03",
    "year": 2023,
    "title": "Caminandes: Llamigos",
    "desc": "Three dogs, zero humans, one very suspicious tennis ball.",
    "id": "otiHE9D3dAI",
    "link": "https://www.lensculture.com"
  }
];
